# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.7

# Command to install dependencies
install:
  - pip install --upgrade pip && pip install -U tox-travis codecov

# Command to run tests
script: tox

after_success: codecov
